iVersion: apps/v1
kind: Deployment
metadata:
  name: automaticcontainrizationazureproject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AutomaticContainrizationAzureProject
  template:
    metadata:
      labels:
        app: AutomaticContainrizationAzureProject
    spec:
      containers:
      - name: dockersamplerepos
        image: g3registry.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: automaticcontainrizationazureproject
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AutomaticContainrizationAzureProject